__include__: ['ecvehicle.yml']

output_dir: outputs/ecvehicle_m

ViTAdapter: {name: ecpose_vittplus, embed_dim: 256, weights_path: ecvits/ecpose_vittplus.pth, interaction_indexes: [10, 11], num_heads: 4}
HybridEncoder: {in_channels: [256, 256, 256], depth_mult: 0.67, expansion: 0.75, hidden_dim: 256, dim_feedforward: 512}
DETRTransformer: {hidden_dim: 256, dim_feedforward: 512, num_decoder_layers: 4}

optimizer:
  type: AdamW
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.0001
