__include__: ['ecvehicle.yml']

output_dir: outputs/ecvehicle_s

ViTAdapter: {name: ecpose_vitt, embed_dim: 192, weights_path: ecvits/ecpose_vitt.pth, interaction_indexes: [10, 11], num_heads: 3}
HybridEncoder: {in_channels: [192, 192, 192], depth_mult: 0.67, expansion: 0.34, hidden_dim: 192, dim_feedforward: 512}
DETRTransformer: {hidden_dim: 192, dim_feedforward: 512, num_decoder_layers: 3}

optimizer:
  type: AdamW
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.0001
