__include__: ['ecdet_pose.yml']
output_dir: outputs/ecdet_pose_l
ViTAdapter: {name: ecvits, embed_dim: 384, num_heads: 6, proj_dim: 256, interaction_indexes: [10, 11], weights_path: ecvits/ecvits.pth}
HybridEncoder: {in_channels: [256, 256, 256], depth_mult: 1, expansion: 0.75, hidden_dim: 256, dim_feedforward: 1024}
DETRTransformer: {hidden_dim: 256, nhead: 8, dim_feedforward: 1024, num_decoder_layers: 4}
